### ISSUE TITLE
Inconsistency in handling query parameters for list and search endpoints

### ISSUE THREAD

**Issue by timeu** [Arabidopsis-Information-Portal/adama#95]
Query parameters are handled differently in the `search` and in the `list` endpoint. 

A query parameter in the `search` endpoint is treated as a normal `key,value` pair ` "limit": 10`, however a query parameter in the `list` endpoint is always handled as a `key,value[]` pair `"limit":[10]`. 

Futhermore the `list` endpoint can handle arrays of parameters: 
`my_service_v_0.1?limit=10,20` --> `"limit":[10,20]` whereas the `search`  endpoint always only takes the first parameter: `"limit":10`. 

BTW both endpoints have the same parameter definition in the `metadata.yml` (example for `search` endpoint):

```yml
endpoints:
    /search:
        parameters:
            - name: LIMIT
              description: How many records should be retrieved
              type: number
              required: false
              format: integer
```

I didn't find anything in the documentation about this.
